sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isamrs-tim16