sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=<generisani_project_key> -Dsonar.organization=stojkovm-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isamrs-tim16